### ISSUE TITLE
✏️ Update "Project Title" in readme

### ISSUE THREAD

**Issue by skadogg** [skadogg/personal-tv-guide#109]
_This would be a great, simple Issue for a new contributor, ideally someone who it just getting started contributing using Github._

Oops, I forgot to change four instances of "Project Title" from the template I was using. These can all be updated to "Personal TV Guide" (bolded, no quotes).

`Project Title` ➡ `**Personal TV Guide**`

**Comment by Ashrick12** [comment]
I'll work on this :)
