### ISSUE TITLE
⚡ Selenium headless mode

### ISSUE THREAD

**Issue by skadogg** [skadogg/personal-tv-guide#20]
Now that this has a good way to gather and store the user's JustWatch credentials, I'd like to see whether it can be run in headless mode. If so, then it could be set to run and update data on a schedule.

**Comment by skadogg** [comment]
This might actually work now. I'm just not sure how Selenium works in anything other than Chrome. It would be great to try this in an environment with no GUI.

**Comment by skadogg** [comment]
@code-master-ajay, it sounds like [PR #42](https://github.com/skadogg/personal-tv-guide/pull/42) resolves this issue, too. Does that seem correct to you?

**Comment by code-master-ajay** [comment]
@skadogg , yes that's correct.
