### ISSUE TITLE
🐛 Occasional errors when scraping pages with Selenium

### ISSUE THREAD

**Issue by skadogg** [skadogg/personal-tv-guide#28]
Certain pages have errors that appear in the terminal when running. This interferes with [progress bars](https://github.com/skadogg/personal-tv-guide/issues/22), so it would be nice to either ignore the errors and skip the output, or create some means of logging errors.

`handshake failed; returned -1, SSL error code 1, net_error -100`

**Comment by code-master-ajay** [comment]
Hi @skadogg, do you know how to reproduce this error, i might be able to solve it.

**Comment by skadogg** [comment]
Hi, Ajay.

I just ran scrape_movies.py on about 900 movies, and it only had a few errors. It looks like one of the offending titles was [_The Vanishing_](https://www.justwatch.com/us/movie/the-vanishing).

![image](https://github.com/skadogg/personal-tv-guide/assets/19212961/3ceada7b-fa24-4356-aa98-4dc058b3d20d)

Or as text, if you prefer:
```
PS C:\Users\gunner\Documents\git\personal-tv-guide> python .\scrape_movies.py

DevTools listening on ws://127.0.0.1:61535/devtools/browser/b76bbbe7-6d3e-473c-a42e-ce38021413e0
<■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■> 45/45 [100%] in 42.0s (1.06/s)
<□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□> ▅▇▇ 5/887 [1%] in 27s (~1:19:29, 0.2/s) /us/movie/the-vanishing[38412:35544:0102/221655.343:ERROR:ssl_client_socket_impl.cc(975)] handshake failed; returned -1, SSL error code 1, net_error -100
<□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□> ▆█▆ 5/887 [1%] in 28s (~1:19:39, 0.2/s) /us/movie/the-vanishing[38412:35544:0102/221655.411:ERROR:ssl_client_socket_impl.cc(975)] handshake failed; returned -1, SSL error code 1, net_error -100
<■■■■■■■■■■■■■■■□□□□□□□□□□□□□□□□□□□□□□□□□> ▆█▆ 322/887 [36%] in 26:45 (~46:55, 0.2/s) /us/movie/the<■■■■■■■■■■■■■■■□□□□□□□□□□□□□□□□□□□□□□□□□> ▄▂▂ 325/887 [37%] in 26:58 (~46:40, 0.2/s) /us/movie/the[34492:25380:0102/224326.149:ERROR:device_event_log_impl.cc(192)] [22:43:26.150] USB: usb_service_win.cc:104 SetupDiGetDeviceProperty({{A45C254E-DF1C-4EFD-8020-67D146A850E0}, 6}) failed: Element not found. (0x490)
<■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■> 887/887 [100%] in 1:13:45.7 (0.20/s)
PS C:\Users\gunner\Documents\git\personal-tv-guide>
```

**Comment by code-master-ajay** [comment]
Hi @skadogg, Thanks for the details, i will try to solve this.

**Comment by code-master-ajay** [comment]
Hi @skadogg , I was able to reproduce the error. I did some digging and i found that the error is occurring because we are requesting the pages from 'justwatch' very frequently without enough time gap. because of this their server rejects a few of the requests. 

i tried adding some delay in the requests, but still a couple of times some of the requests fail.

Right now what we can do is that we add a try catch to catch such failed requests and skip that movie's data.

Please let me know if this sounds good to you, then i will create a PR for the same.

**Comment by skadogg** [comment]
Nice job figuring this out, Ajay! Yes, I think this will be a good solution.
