### ISSUE TITLE
dev_mode variable in scrapers needs more thought

### ISSUE THREAD

**Issue by skadogg** [skadogg/personal-tv-guide#31]
Code runs fine when you run a selection, but give error when run from terminal.

`NameError: name 'dev_mode' is not defined`

**Comment by LeonardoBringel** [comment]
I think my merge request #30 actually fixed this issue since I'm setting it to False by default if DEV_MODE is not provided in the .env file 😉

**Comment by skadogg** [comment]
> I think my merge request #30 actually fixed this issue since I'm setting it to False by default if DEV_MODE is not provided in the .env file 😉

Oh, nice! I'll take a look at that request in a little while. Thanks for helping with this!
