### ISSUE TITLE
⚡ Block image loading when using Selenium

### ISSUE THREAD

**Issue by skadogg** [skadogg/personal-tv-guide#33]
It sounds like we can minimize bandwidth usage by not loading images with Selenium. Here's [some more info](https://scrapfly.io/blog/how-to-block-image-loading-in-selenium/).

**Comment by ajjubhai** [comment]
Hi @skadogg , i have hands on experience with selenium. Can i take this up ?

**Comment by skadogg** [comment]
> Hi @skadogg , i have hands on experience with selenium. Can i take this up ?

That would be wonderful! Thanks for the help!
