### ISSUE TITLE
🔧 Put use_keyword_lists in .env file

### ISSUE THREAD

**Issue by skadogg** [skadogg/personal-tv-guide#49]
_use_keyword_lists_ is currently hard-coded in _build_html.py_. This can be moved to the .env file just like the other variables. The default can be _False_, and we can say that it is not required in the readme file.

**Comment by rudransh61** [comment]
Can I do this ?

**Comment by skadogg** [comment]
Yes, thank you for offering to help! I'll assign the issue to you.

**Comment by rudransh61** [comment]
@skadogg 
Pls review th pr

**Comment by rudransh61** [comment]
done , is it now ready to merge ?
