### ISSUE TITLE
✨ Randomize start time in each row

### ISSUE THREAD

**Issue by skadogg** [skadogg/personal-tv-guide#5]
Right now, every row has its first show start right on the hour. What if most shows start on the hour, some shows start 15 minutes later, and a few shows start after a half hour?

Here's what I imagine it would look like:

![image](https://github.com/skadogg/personal-tv-guide/assets/19212961/bd73a1fc-86d4-4343-8f71-45dbc9acb1fa)

**Comment by eadaradhiraj** [comment]
I Would like to try

**Comment by skadogg** [comment]
Great! Go for it!

**Comment by skadogg** [comment]
@eadaradhiraj Thanks for offering to help with this! Just a heads-up: there have been a couple changes today, so you'll probably want to sync with the main branch before too long.

**Comment by eadaradhiraj** [comment]
> @eadaradhiraj Thanks for offering to help with this! Just a heads-up: there have been a couple changes today, so you'll probably want to sync with the main branch before too long.

OK will keep in mind

**Comment by skadogg** [comment]
@eadaradhiraj, I would really appreciate your help if you are still interested. I think this would just involve adding a column with a random colspan in the generate_html_genre_tds() function.

If you are no longer interested, please just let me know and I'll figure out a new plan.

Thanks either way!

**Comment by eadaradhiraj** [comment]
> @eadaradhiraj, I would really appreciate your help if you are still interested. I think this would just involve adding a column with a random colspan in the generate_html_genre_tds() function.
> 
> If you are no longer interested, please just let me know and I'll figure out a new plan.
> 
> Thanks either way!

Sorry for the delay. `python build_html.py` is throwing an error, `FileNotFoundError: [Errno 2] No such file or directory: './saved_data_genres.bin'`

**Comment by skadogg** [comment]
Shoot, I bet that's my fault. After you have the other .bin files for movies and TV, you can run get_genres_from_scraped_lists() to generate the genre .bin file. Then things should work. Sorry about that. I'll need to go back and clean up this older process.

**Comment by eadaradhiraj** [comment]
![image](https://github.com/skadogg/personal-tv-guide/assets/28575339/cb411d49-68b4-4037-85c5-c842782a2390)

I am getting something like this. I don't know why though

**Comment by skadogg** [comment]
If you run the movie and TV scrape programs successfully, the show data will get stored in a couple .bin files. Once you have these, the build code will be able to read them and write the data to the HTML table.

I'll also make some time to create a couple small sample .bin files for easier testing.

**Comment by skadogg** [comment]
> I'll also make some time to create a couple small sample .bin files for easier testing.

I was able to get this done. If you pull the latest from main, you'll see a new folder with the sample .bin files, and you can just copy them to the root folder.

**Comment by eadaradhiraj** [comment]
![image](https://github.com/skadogg/personal-tv-guide/assets/28575339/08a2a153-01f9-417c-8f7a-2ae987796986)

Am I missing something?

**Comment by skadogg** [comment]
I'm not really sure why it's not working for you. Sorry for all the trouble, @eadaradhiraj. I did just add some error checking today, so hopefully updating to the latest code will help.

**Comment by eadaradhiraj** [comment]
> generate_html_genre_tds

ok I am able to run this now. There is `this_colspan`. Do you intend that to be random?

**Comment by skadogg** [comment]
I'm glad you got it working! Thanks for your dedication to helping with this issue!

Like the mock-up shows, I'm hoping to see some random-width <td> tags to the right of the first column (the genre name). They should be between 0 (nothing inserted) and 3 (colspan: 3) columns wide. By doing this, it gives the user a better chance of having a show start right at the time they want to begin watching. 📺

**Comment by eadaradhiraj** [comment]
![image](https://github.com/skadogg/personal-tv-guide/assets/28575339/6c84bdf9-6317-4684-9f2a-80af66a3c1ba)
Would this be something you would like?

**Comment by skadogg** [comment]
No, you can't really watch a full movie in 15 minutes, so this won't work. Here's a mockup of how this should look:

![image](https://github.com/skadogg/personal-tv-guide/assets/19212961/2f8bbdec-6ead-4f83-a668-05ae533f45d5)

```
<table>
<tr>
<th>&nbsp;</th>
<th>3</th><th>&nbsp;</th><th>&nbsp;</th><th>&nbsp;</th>
<th>4</th><th>&nbsp;</th><th>&nbsp;</th><th>&nbsp;</th>
<th>5</th><th>&nbsp;</th><th>&nbsp;</th><th>&nbsp;</th>
<th>6</th><th>&nbsp;</th><th>&nbsp;</th><th>&nbsp;</th>
</tr>
<tr><td class="genre">Drama</td>
<td colspan="1"></td>
<td colspan="7"><a href="https://www.justwatch.com/us/movie/prince-avalanche"><img src="https://img.shields.io/badge/Prince Avalanche (2013) - R-bf616a?labelColor=4c566a"></a></td>
<td colspan="7"><a href="https://www.justwatch.com/us/movie/hoovey"><img src="https://img.shields.io/badge/Hoovey (2015) - PG-a3be8c?labelColor=4c566a"></a></td>
<td colspan="2"><a href="https://www.justwatch.com/us/tv-show/batman-the-animated-series"><img src="https://img.shields.io/badge/Batman: The Animated Series - TV--PG-a3be8c?labelColor=4c566a"></a></td>
</tr>
<tr><td class="genre">Reality TV</td>
<td colspan="2"></td>
<td colspan="4"><a href="https://www.justwatch.com/us/tv-show/down-for-love"><img src="https://img.shields.io/badge/Down for Love - TV--PG-a3be8c?labelColor=4c566a"></a></td>
</tr>
<tr><td class="genre">Action & Adventure</td>
<td colspan="1"></td>
<td colspan="5"><a href="https://www.justwatch.com/us/movie/batman-year-one"><img src="https://img.shields.io/badge/Batman: Year One (2011) - PG--13-5e81ac?labelColor=4c566a"></a></td>
</tr>
<tr><td class="genre">Music & Musical</td>
<td colspan="2"></td>
<td colspan="7"><a href="https://www.justwatch.com/us/movie/herbie-hancock-possibilities"><img src="https://img.shields.io/badge/Herbie Hancock: Possibilities (2006) -  -b48ead?labelColor=4c566a"></a></td>
</tr>
<tr><td class="genre">Romance</td>
<td colspan="2"><a href="https://www.justwatch.com/us/tv-show/will-and-grace"><img src="https://img.shields.io/badge/Will & Grace - TV--14-5e81ac?labelColor=4c566a"></a></td>
</tr>
<tr><td class="genre">Mystery & Thriller</td>
<td colspan="1"></td>
<td colspan="8"><a href="https://www.justwatch.com/us/movie/the-vanishing"><img src="https://img.shields.io/badge/The Vanishing (1988) -  -b48ead?labelColor=4c566a"></a></td>
</tr>
</table>
```

Whereever you see something like `<td colspan="2"></td>`, this is a random-width blank column.

Here is an idea on how to make this happen:

```
def generate_html_genre_tds(genre_list, genre, hours, random_start = False):
    str = '<tr><td class="genre">' + genre + '</td>\n'
    
    if random_start:
        i = random_start_time()
        if i > 0:
            str += generate_table_td('', i)
    else:
        i = 0

    time_countdown = hours * 4
    for i in range(len(genre_list)):
```

**Comment by skadogg** [comment]
Hi, @eadaradhiraj. I've given it some thought, and I decided to handle this issue on my own. I want to get started on [refactoring the code](#52 ), and this is the last piece before I can begin that. I do appreciate that you tried getting this working, and I hope we can collaborate again in the future!

**Comment by eadaradhiraj** [comment]
Sure @skadogg. Thank you for the opportunity. I also had too much on my plate. Sorry I couldn't contribute to the best of my ability
