### ISSUE TITLE
💄 Logo / brandmark for Personal TV Guide

### ISSUE THREAD

**Issue by skadogg** [skadogg/personal-tv-guide#51]
We need a logo! It would be great to have someone create a quick logo and/or brandmark that we could put at the top of output page(s) and the top of the readme file. I'm not stuck on the green icon in the readme. Please feel free to use your creativity!

**Comment by code-master-ajay** [comment]
Hi @skadogg , Here are a few AI generated ones.

![personal_tv_guide](https://github.com/skadogg/personal-tv-guide/assets/21195835/a11e7e7e-25cc-4237-9268-aa608702fa2e)
![personal_tv_guide_2](https://github.com/skadogg/personal-tv-guide/assets/21195835/233b909a-9465-4f06-ab5b-4c4932fd4806)

**Comment by Khaleelhabeeb** [comment]
@skadogg, here is a suggestion
![personal tv guide](https://github.com/skadogg/personal-tv-guide/assets/115427472/cc323cb2-e0df-453e-ace1-409f5bc1c37b)

**Comment by skadogg** [comment]
Thanks for the responses, guys! These are all nice ideas. I didn't even consider AI images, but I guess I was hoping for something more "personal."

@Khaleelhabeeb, is your image something that you designed?

**Comment by Khaleelhabeeb** [comment]
@skadogg , yeah i designed the logo using canva

**Comment by skadogg** [comment]
Fixed by #54
