### ISSUE TITLE
🐛 Minor Bug Found

### ISSUE THREAD

**Issue by code-master-ajay** [skadogg/personal-tv-guide#58]
In the latest commit for Putting the USE_KEYWORD_LIST in the env file, i found an error in the code

in build_html.py 

```
use_keyword_lists = int(os.environ.get('USE_KEYWORD_LIST'))
```

should be casted to boolean and not to integer
the correct code should be

```
use_keyword_lists = bool(os.environ.get('USE_KEYWORD_LIST'))
```

I will make a PR to fix this, please review and merge it.

**Comment by skadogg** [comment]
Shoot. I missed that when reviewing, but the code did seem to run correctly when casting to an int. Strange. Thanks for finding this, Ajay.
