### ISSUE TITLE
🍱 Edit existing image for page header

### ISSUE THREAD

**Issue by skadogg** [skadogg/personal-tv-guide#61]
I would love to use the current image (personal_tv_guide.png) at the top of the webpage, but it's a bit tall for this purpose. Here's what I'm thinking, but please feel free to play around with the alignment and pick what you think looks best.

![image](https://github.com/skadogg/personal-tv-guide/assets/19212961/3908ba7f-49a5-4e66-8719-47c43a4d3879)

**Comment by skadogg** [comment]
And yes, I recognize the irony in using an image editor to request changes to an image. 🤣 I used SnagIt for this, but I'm not great at proper image editors.

**Comment by Khaleelhabeeb** [comment]
@skadogg, do you mean at the top of out.html or the repository readme

**Comment by skadogg** [comment]
I suppose it could go at the top of both, but I was only thinking of the HTML. Your choice.
