### ISSUE TITLE
🚸 Get image link to show cover art for Featured Film

### ISSUE THREAD

**Issue by skadogg** [skadogg/personal-tv-guide#66]
I tried figuring out how to scrape the cover art from JustWatch, but I couldn't quite get there on my own. I would like to see something like this mockup:

![image](https://github.com/skadogg/personal-tv-guide/assets/19212961/a0c07fc8-74b6-4f44-8e27-378821653987)

(I manually made the mockup by manually modifying the HTML:

```
<table width="800px">
<tr><th colspan="3">Featured Film</th></tr>
<tr><td rowspan="3"><img src="https://images.justwatch.com/poster/144168725/s276/prince-avalanche.jpg"><img></td><td><a href="https://www.justwatch.com/us/movie/prince-avalanche"><img src="https://img.shields.io/badge/Prince Avalanche (2013) - R-bf616a?labelColor=4c566a"></a></td><td rowspan="3">Two highway road workers spend the summer of 1988 away from their city lives. The isolated landscape becomes a place of misadventure as the men find themselves at odds with each other and the women they left behind.</td></tr>
<tr><td>Comedy, Drama</td></tr>
<tr><td>1h 34min</td></tr>
</table>
```

**Comment by code-master-ajay** [comment]
Hi @skadogg, I will like to take this up.

**Comment by skadogg** [comment]
Sounds great. Thanks, Ajay!

**Comment by skadogg** [comment]
![image](https://github.com/skadogg/personal-tv-guide/assets/19212961/735264f0-1e0b-473f-b788-837e30409bc2)
