### ISSUE TITLE
🔒 Mask password entry in terminal

### ISSUE THREAD

**Issue by skadogg** [skadogg/personal-tv-guide#71]
When first setting up the project, we are prompted to enter an email address and password. The password is shown in the terminal and stays visible during the entire run. I think it would be good to hide this, either by clearing the buffer or by masking with ******'s.

**Comment by skadogg** [comment]
I think [this](https://docs.python.org/3/library/getpass.html) might be what we need here. Anyone have experience with `getpass()`?

**Comment by code-master-ajay** [comment]
Hi @skadogg, i will take this up.
