### ISSUE TITLE
💄 Why are these different sizes?

### ISSUE THREAD

**Issue by skadogg** [skadogg/personal-tv-guide#91]
I just noticed that the left and right sides of the badges / shields are different sizes. Here's what I see, zoomed to 250%:

![image](https://github.com/skadogg/personal-tv-guide/assets/19212961/82ef489f-0b8b-4ce8-90a2-0f3ce03e3081)

This is probably just some kind of padding or spacing thing in nord.css. It would be great to have the right side be a bit bigger to match the size of the left.

**Comment by code-master-ajay** [comment]
Hi @skadogg, i can see in the nord.css file 
 
For badge_main the padding is 5px.
https://github.com/skadogg/personal-tv-guide/blob/3c2641490533460ae4429187cb4b858bd736b919/css/nord.css#L278

and for other badges red,green and blue the padding is 3px.
https://github.com/skadogg/personal-tv-guide/blob/3c2641490533460ae4429187cb4b858bd736b919/css/nord.css#L302

maybe this is causing the issue.

Please let me know if this is correct, so i will open a PR for this.

**Comment by skadogg** [comment]
Hi, @code-master-ajay. You're right; I see the padding is too small for R, G, B, and badge_other. Would you please switch them all to 5px?

**Comment by code-master-ajay** [comment]
@skadogg Done.

**Comment by skadogg** [comment]
Thanks, @code-master-ajay!
