### ISSUE TITLE
🐛 Error when saved_data.bin does not yet exist

### ISSUE THREAD

**Issue by skadogg** [skadogg/personal-tv-guide#94]
We need to test for the existance of saved_data.bin before trying to read from it. If it's not there, show_db should be initialized as an empty list.

```
PS C:\Users\gunner\Documents\git\personal-tv-guide> & c:/Users/gunner/Documents/git/personal-tv-guide/.venv/Scripts/python.exe c:/Users/gunner/Documents/git/personal-tv-guide/run.py

DevTools listening on ws://127.0.0.1:55958/devtools/browser/c7325439-6987-4945-82c9-57fb77f619e0
Signed in successfully
Traceback (most recent call last):
  File "c:\Users\gunner\Documents\git\personal-tv-guide\run.py", line 31, in <module>
    modules.justwatch.scrape_justwatch('TV')
  File "c:\Users\gunner\Documents\git\personal-tv-guide\modules\justwatch.py", line 157, in scrape_justwatch 
    show_db = modules.data_bin_convert.bin_to_data('./my_data/saved_data.bin')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\gunner\Documents\git\personal-tv-guide\modules\data_bin_convert.py", line 18, in bin_to_data
    fh = open(filename, 'rb')
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './my_data/saved_data.bin'

```PS C:\Users\gunner\Documents\git\personal-tv-guide>

**Comment by r3dp0int** [comment]
you should just be able to do this with try except blocks

**Comment by skadogg** [comment]
I bet you're right, @r3dp0int. Sounds like a _good first issue_ 😉 for someone who wants an easy way to begin contributing. Thanks for the suggestion!

**Comment by r3dp0int** [comment]
Which Python version are you using for this project?

**Comment by skadogg** [comment]
I'm pretty new to Python, so I'm using 3.12, though I don't know that there's anything too special going on that it wouldn't work with one or two earlier versions. I haven't tested with anything else yet.

**Comment by r3dp0int** [comment]
I've created a check for my data directory which will create it if it doesn't exist, and have implemented a check for the .bin file. Will finish implementing creation of the blank .bin file then issue a pull request for you 😄

**Comment by skadogg** [comment]
#98 does fix this for me.

![image](https://github.com/skadogg/personal-tv-guide/assets/19212961/d7329962-dc53-439d-9e6d-28419b2f4efc)
